UPDATE INTEGRATION_GROUPS
SET DISPLAY_NAME = 'Notification Service',
    NAME         = 'NOTIFICATION_SERVICE'
WHERE NAME = 'SLACK';

ALTER TABLE test_runs
    RENAME COLUMN slack_channels TO channels;

DO
$$
    DECLARE
        INTEGRATION_GROUP_ID INTEGRATION_GROUPS.id%TYPE;
        INTEGRATION_TYPE_ID  INTEGRATION_TYPES.id%TYPE;
        INTEGRATION_ID       INTEGRATIONS.id%TYPE;
        INTEGRATION_PARAM_ID INTEGRATION_PARAMS.id%TYPE;

    BEGIN
        SELECT ID INTO INTEGRATION_GROUP_ID FROM INTEGRATION_GROUPS WHERE NAME = 'NOTIFICATION_SERVICE';

        IF NOT EXISTS(SELECT ID FROM INTEGRATION_TYPES WHERE NAME = 'MICROSOFT_TEAMS')
        THEN
            INSERT INTO INTEGRATION_TYPES(NAME, DISPLAY_NAME, ICON_URL, INTEGRATION_GROUP_ID)
            VALUES ('MICROSOFT_TEAMS', 'Microsoft Teams', '', INTEGRATION_GROUP_ID)
            RETURNING ID INTO INTEGRATION_TYPE_ID;

            INSERT INTO INTEGRATIONS(NAME, INTEGRATION_TYPE_ID, is_default)
            VALUES ('MICROSOFT_TEAMS', INTEGRATION_TYPE_ID, TRUE)
            RETURNING ID INTO INTEGRATION_ID;

            INSERT INTO INTEGRATION_PARAMS(NAME, MANDATORY, INTEGRATION_TYPE_ID, NEED_ENCRYPTION)
            VALUES ('MICROSOFT_TEAMS_WEB_HOOK', TRUE, INTEGRATION_TYPE_ID, FALSE)
            RETURNING ID INTO INTEGRATION_PARAM_ID;

            INSERT INTO INTEGRATION_SETTINGS(INTEGRATION_ID, INTEGRATION_PARAM_ID)
            VALUES (INTEGRATION_ID, INTEGRATION_PARAM_ID);

        ELSE
        END IF;

    END
$$;
