ALTER TABLE test_runs DROP COLUMN IF EXISTS framework;
ALTER TABLE test_runs DROP COLUMN IF EXISTS ended_at;
ALTER TABLE tests DROP COLUMN IF EXISTS uuid;
DROP INDEX IF EXISTS uuid_test_unique;

ALTER TABLE test_runs ADD COLUMN framework VARCHAR(50) NULL;
ALTER TABLE test_runs ADD COLUMN ended_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tests ADD COLUMN uuid TEXT NULL;
CREATE UNIQUE INDEX uuid_test_unique ON tests (test_run_id, uuid) WHERE uuid IS NOT NULL;