DO
$$
    DECLARE
        INTEGRATION_PARAM_ID_VAR INTEGRATION_PARAMS.id%TYPE;
    BEGIN

        FOR INTEGRATION_PARAM_ID_VAR IN SELECT ID FROM INTEGRATION_PARAMS WHERE NAME IN ('EMAIL_USER', 'EMAIL_PASSWORD')
            LOOP
                UPDATE INTEGRATION_PARAMS SET MANDATORY = FALSE WHERE ID = INTEGRATION_PARAM_ID_VAR;
            END LOOP;

    END
$$;